# version: "3.9"

services:
  web:
    build: .
    container_name: nexus_backend
    command: >
      sh -c "
      python movie_backend/manage.py migrate &&
      python movie_backend/manage.py collectstatic --noinput &&
      # gunicorn --chdir movie_backend movie_backend.wsgi:application --bind 0.0.0.0:8000
      CMD gunicorn --chdir movie_backend movie_backend.wsgi:application --bind 0.0.0.0:$PORT
      "
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: nexus_postgres
    restart: always
    environment:
      POSTGRES_DB: movies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nexus_redis

  nginx:
    image: nginx:alpine
    container_name: nexus_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app
    depends_on:
      - web

volumes:
  postgres_data:
